export { testApiConsistencyAcrossLayers } from './apiConsistencyTests';
export { testCheckFunctionality } from './checkFunctionality';
export { testClearFunctionality } from './clearFunctionality';
export { testClickFunctionality } from './clickFunctionality';
export { testDblclickFunctionality } from './dblclickFunctionality';
export { testDispatchEventFunctionality } from './dispatchEventFunctionality';
export { testEvaluateFunctionality } from './evaluateFunctionality';
export { testFillFunctionality } from './fillFunctionality';
export { testFrameMissingMethodsFunctionality } from './frameMissingMethodsFunctionality';
export { testHighlightFunctionality } from './highlightFunctionality';
export { testLocatorFunctionality } from './locatorFunctionality';
export { testMissingMethodsFunctionality } from './missingMethodsFunctionality';
export { testPageMissingMethodsFunctionality } from './pageMissingMethodsFunctionality';
export * from './testUtils';
